// Flat config (current ESLint default). Covers packages/schemas/typescript
// only — apps/web has its own eslint.config.mjs (eslint-config-next: React
// hooks rules, a11y, Next-specific checks) generated by create-next-app and
// is linted via `pnpm --filter web lint` / `.github/workflows/ci.yml`'s
// ts-lint job, not this file. Deliberately not duplicated here (Thato's
// call, made once apps/web actually existed — see PLANNING.md).
import js from "@eslint/js";
import tseslint from "typescript-eslint";
import eslintConfigPrettier from "eslint-config-prettier";

export default [
  { ignores: ["**/node_modules/**", "**/.next/**", "**/dist/**", "**/.turbo/**", "**/.dist/**"] },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  eslintConfigPrettier,
  {
    files: ["packages/schemas/typescript/**/*.ts"],
    languageOptions: {
      parserOptions: { ecmaVersion: "latest", sourceType: "module" },
    },
  },
];
