"""initial schema per database-design.md

Revision ID: 81f156df0484
Revises:
Create Date: 2026-09-14 16:10:21.670467
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "81f156df0484"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project")),
    )
    op.create_table(
        "target",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("base_url", sa.String(length=2048), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("authorization_confirmed", sa.Boolean(), nullable=False),
        sa.Column("authorization_confirmed_by", sa.String(length=255), nullable=True),
        sa.Column("authorization_confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            name=op.f("fk_target_project_id_project"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_target")),
    )
    op.create_index(op.f("ix_target_project_id"), "target", ["project_id"], unique=False)
    op.create_table(
        "test_plan",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column(
            "test_type",
            sa.Enum(
                "load",
                "stress",
                "spike",
                "endurance",
                "capacity",
                "baseline",
                "regression",
                name="test_type",
            ),
            nullable=False,
        ),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("target_concurrency", sa.Integer(), nullable=False),
        sa.Column("ramp_strategy", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("user_journeys", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("thresholds", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("duration", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("stages", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("success_criteria", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("controlled_variable", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "status",
            sa.Enum("proposed", "approved", "superseded", name="test_plan_status"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            name=op.f("fk_test_plan_project_id_project"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["target.id"],
            name=op.f("fk_test_plan_target_id_target"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_test_plan")),
    )
    op.create_index(op.f("ix_test_plan_project_id"), "test_plan", ["project_id"], unique=False)
    op.create_index(op.f("ix_test_plan_target_id"), "test_plan", ["target_id"], unique=False)
    op.create_table(
        "test_run",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("test_plan_id", sa.Uuid(), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "succeeded",
                "failed",
                "aborted_over_limit",
                name="test_run_status",
            ),
            nullable=False,
        ),
        sa.Column("k6_script_ref", sa.String(length=1024), nullable=True),
        sa.Column("raw_output_ref", sa.String(length=1024), nullable=True),
        sa.Column("clamped", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["target.id"],
            name=op.f("fk_test_run_target_id_target"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["test_plan_id"],
            ["test_plan.id"],
            name=op.f("fk_test_run_test_plan_id_test_plan"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_test_run")),
    )
    op.create_index(
        "ix_test_run_status_active",
        "test_run",
        ["status"],
        unique=False,
        postgresql_where="status IN ('queued', 'running')",
    )
    op.create_index(op.f("ix_test_run_target_id"), "test_run", ["target_id"], unique=False)
    op.create_index(op.f("ix_test_run_test_plan_id"), "test_run", ["test_plan_id"], unique=False)
    op.create_table(
        "investigation",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column(
            "objective",
            sa.Enum(
                "determine_capacity",
                "diagnose_regression",
                "validate_fix",
                "baseline",
                name="investigation_objective",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "planning",
                "running",
                "investigating",
                "experimenting",
                "reporting",
                "complete",
                "failed",
                name="investigation_status",
            ),
            nullable=False,
        ),
        sa.Column("baseline_test_run_id", sa.Uuid(), nullable=True),
        sa.Column("current_test_run_id", sa.Uuid(), nullable=True),
        sa.Column("experiments_run", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["baseline_test_run_id"],
            ["test_run.id"],
            name=op.f("fk_investigation_baseline_test_run_id_test_run"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["current_test_run_id"],
            ["test_run.id"],
            name=op.f("fk_investigation_current_test_run_id_test_run"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            name=op.f("fk_investigation_project_id_project"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["target.id"],
            name=op.f("fk_investigation_target_id_target"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_investigation")),
    )
    op.create_index(
        op.f("ix_investigation_project_id"), "investigation", ["project_id"], unique=False
    )
    op.create_index(
        "ix_investigation_status_active",
        "investigation",
        ["status"],
        unique=False,
        postgresql_where="status NOT IN ('complete', 'failed')",
    )
    op.create_index(
        op.f("ix_investigation_target_id"), "investigation", ["target_id"], unique=False
    )
    op.create_table(
        "metric",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("test_run_id", sa.Uuid(), nullable=False),
        sa.Column("endpoint", sa.String(length=2048), nullable=True),
        sa.Column("p50_ms", sa.Float(), nullable=False),
        sa.Column("p90_ms", sa.Float(), nullable=False),
        sa.Column("p95_ms", sa.Float(), nullable=False),
        sa.Column("p99_ms", sa.Float(), nullable=False),
        sa.Column("throughput_rps", sa.Float(), nullable=False),
        sa.Column("error_rate", sa.Float(), nullable=False),
        sa.Column("concurrency", sa.Integer(), nullable=False),
        sa.Column(
            "http_status_distribution", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["test_run_id"],
            ["test_run.id"],
            name=op.f("fk_metric_test_run_id_test_run"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_metric")),
    )
    op.create_index(op.f("ix_metric_test_run_id"), "metric", ["test_run_id"], unique=False)
    op.create_table(
        "test_stage",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("test_run_id", sa.Uuid(), nullable=False),
        sa.Column("target_vus", sa.Integer(), nullable=False),
        sa.Column("duration_s", sa.Integer(), nullable=False),
        sa.Column("sequence_index", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["test_run_id"],
            ["test_run.id"],
            name=op.f("fk_test_stage_test_run_id_test_run"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_test_stage")),
        sa.UniqueConstraint(
            "test_run_id", "sequence_index", name=op.f("uq_test_stage_test_run_id_sequence_index")
        ),
    )
    op.create_index(op.f("ix_test_stage_test_run_id"), "test_stage", ["test_run_id"], unique=False)
    op.create_table(
        "ai_execution",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("investigation_id", sa.Uuid(), nullable=True),
        sa.Column("test_run_id", sa.Uuid(), nullable=True),
        sa.Column(
            "agent",
            sa.Enum(
                "orchestrator",
                "test_planner",
                "load_engineer",
                "performance_investigator",
                "reporting",
                name="agent_name",
            ),
            nullable=False,
        ),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("input_reference", sa.String(length=1024), nullable=False),
        sa.Column("output_reference", sa.String(length=1024), nullable=False),
        sa.Column("decision", sa.Text(), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["investigation_id"],
            ["investigation.id"],
            name=op.f("fk_ai_execution_investigation_id_investigation"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["test_run_id"],
            ["test_run.id"],
            name=op.f("fk_ai_execution_test_run_id_test_run"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_execution")),
    )
    op.create_index(
        op.f("ix_ai_execution_investigation_id"), "ai_execution", ["investigation_id"], unique=False
    )
    op.create_table(
        "finding",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("investigation_id", sa.Uuid(), nullable=False),
        sa.Column(
            "severity",
            sa.Enum("CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO", name="severity"),
            nullable=False,
        ),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("observations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["investigation_id"],
            ["investigation.id"],
            name=op.f("fk_finding_investigation_id_investigation"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_finding")),
    )
    op.create_index(
        op.f("ix_finding_investigation_id"), "finding", ["investigation_id"], unique=False
    )
    op.create_table(
        "report",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("investigation_id", sa.Uuid(), nullable=False),
        sa.Column("executive_summary", sa.Text(), nullable=False),
        sa.Column("capacity", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("key_metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("bottleneck_analysis", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("regression", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["investigation_id"],
            ["investigation.id"],
            name=op.f("fk_report_investigation_id_investigation"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report")),
        sa.UniqueConstraint("investigation_id", name=op.f("uq_report_investigation_id")),
    )
    op.create_table(
        "hypothesis",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("finding_id", sa.Uuid(), nullable=False),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("proposed", "testing", "supported", "rejected", name="hypothesis_status"),
            nullable=False,
        ),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("recommended_experiment", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence >= 0.0 AND confidence <= 1.0", name=op.f("ck_hypothesis_confidence_range")
        ),
        sa.ForeignKeyConstraint(
            ["finding_id"],
            ["finding.id"],
            name=op.f("fk_hypothesis_finding_id_finding"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hypothesis")),
    )
    op.create_index(op.f("ix_hypothesis_finding_id"), "hypothesis", ["finding_id"], unique=False)
    op.create_table(
        "experiment",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("hypothesis_id", sa.Uuid(), nullable=False),
        sa.Column("test_plan_id", sa.Uuid(), nullable=False),
        sa.Column("test_run_id", sa.Uuid(), nullable=False),
        sa.Column("variable_changed", sa.String(length=255), nullable=False),
        sa.Column("baseline_value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("experiment_value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["hypothesis_id"],
            ["hypothesis.id"],
            name=op.f("fk_experiment_hypothesis_id_hypothesis"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["test_plan_id"],
            ["test_plan.id"],
            name=op.f("fk_experiment_test_plan_id_test_plan"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["test_run_id"],
            ["test_run.id"],
            name=op.f("fk_experiment_test_run_id_test_run"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_experiment")),
    )
    op.create_index(
        op.f("ix_experiment_hypothesis_id"), "experiment", ["hypothesis_id"], unique=False
    )
    op.create_table(
        "recommendation",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("hypothesis_id", sa.Uuid(), nullable=False),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column(
            "priority",
            sa.Enum("CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO", name="severity"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["hypothesis_id"],
            ["hypothesis.id"],
            name=op.f("fk_recommendation_hypothesis_id_hypothesis"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recommendation")),
    )
    op.create_index(
        op.f("ix_recommendation_hypothesis_id"), "recommendation", ["hypothesis_id"], unique=False
    )
    op.create_table(
        "experiment_result",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("experiment_id", sa.Uuid(), nullable=False),
        sa.Column("comparison", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "conclusion",
            sa.Enum(
                "hypothesis_supported",
                "hypothesis_rejected",
                "inconclusive",
                name="experiment_conclusion",
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiment.id"],
            name=op.f("fk_experiment_result_experiment_id_experiment"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_experiment_result")),
        sa.UniqueConstraint("experiment_id", name=op.f("uq_experiment_result_experiment_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("experiment_result")
    op.drop_index(op.f("ix_recommendation_hypothesis_id"), table_name="recommendation")
    op.drop_table("recommendation")
    op.drop_index(op.f("ix_experiment_hypothesis_id"), table_name="experiment")
    op.drop_table("experiment")
    op.drop_index(op.f("ix_hypothesis_finding_id"), table_name="hypothesis")
    op.drop_table("hypothesis")
    op.drop_table("report")
    op.drop_index(op.f("ix_finding_investigation_id"), table_name="finding")
    op.drop_table("finding")
    op.drop_index(op.f("ix_ai_execution_investigation_id"), table_name="ai_execution")
    op.drop_table("ai_execution")
    op.drop_index(op.f("ix_test_stage_test_run_id"), table_name="test_stage")
    op.drop_table("test_stage")
    op.drop_index(op.f("ix_metric_test_run_id"), table_name="metric")
    op.drop_table("metric")
    op.drop_index(op.f("ix_investigation_target_id"), table_name="investigation")
    op.drop_index(
        "ix_investigation_status_active",
        table_name="investigation",
        postgresql_where="status NOT IN ('complete', 'failed')",
    )
    op.drop_index(op.f("ix_investigation_project_id"), table_name="investigation")
    op.drop_table("investigation")
    op.drop_index(op.f("ix_test_run_test_plan_id"), table_name="test_run")
    op.drop_index(op.f("ix_test_run_target_id"), table_name="test_run")
    op.drop_index(
        "ix_test_run_status_active",
        table_name="test_run",
        postgresql_where="status IN ('queued', 'running')",
    )
    op.drop_table("test_run")
    op.drop_index(op.f("ix_test_plan_target_id"), table_name="test_plan")
    op.drop_index(op.f("ix_test_plan_project_id"), table_name="test_plan")
    op.drop_table("test_plan")
    op.drop_index(op.f("ix_target_project_id"), table_name="target")
    op.drop_table("target")
    op.drop_table("project")
    # ### end Alembic commands ###

    # Hand-added, not autogenerated. Alembic emits CREATE TYPE for each
    # sa.Enum column on the way up but never DROP TYPE on the way down, so
    # without this a downgrade leaves all nine types orphaned and the next
    # `upgrade` dies on "type test_type already exists" — which breaks the
    # downgrade/re-upgrade cycle anyone iterating on migrations relies on.
    for enum_name in (
        "agent_name",
        "experiment_conclusion",
        "hypothesis_status",
        "investigation_objective",
        "investigation_status",
        "severity",
        "test_plan_status",
        "test_run_status",
        "test_type",
    ):
        op.execute(sa.text(f"DROP TYPE IF EXISTS {enum_name}"))
