"""baseline selection for deterministic comparison (issue #34)

Adds the `baseline` table only. Everything else this database needs already
exists.

NOTE for whoever next runs `--autogenerate`: it will also want to rename four
`investigation_event` unique constraints. That is real, pre-existing drift
between #35's migration and the naming convention in `db/base.py` — the
columns are identical, only the generated names differ. It is deliberately
NOT fixed here: `investigation_event` is #35's table, and renaming another
owner's constraints inside this PR would be an unrelated change to someone
else's schema. Raised separately so it can be fixed by its owner.

Revision ID: 49218513a29e
Revises: 4b7e0c2f1a35
Create Date: 2026-09-24 22:46:01.058250
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "49218513a29e"
down_revision: str | None = "4b7e0c2f1a35"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "baseline",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("test_run_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("selected_by", sa.String(length=255), nullable=False),
        sa.Column(
            "test_type",
            # create_type=False: `test_type` is the same Postgres ENUM the
            # initial migration created for test_plan. Autogenerate emits a
            # bare sa.Enum here, which makes this migration try to CREATE TYPE
            # a second time and fail with "type test_type already exists",
            # rolling the whole upgrade back. Reuse the existing type instead.
            # (local-development.md#changing-the-schema flags enums as the one
            # thing autogenerate reliably gets wrong.)
            postgresql.ENUM(
                "load",
                "stress",
                "spike",
                "endurance",
                "capacity",
                "baseline",
                "regression",
                name="test_type",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("target_concurrency", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "target_concurrency > 0", name=op.f("ck_baseline_target_concurrency_positive")
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["target.id"],
            name=op.f("fk_baseline_target_id_target"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["test_run_id"],
            ["test_run.id"],
            name=op.f("fk_baseline_test_run_id_test_run"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_baseline")),
        sa.UniqueConstraint(
            "target_id", "idempotency_key", name=op.f("uq_baseline_target_id_idempotency_key")
        ),
        sa.UniqueConstraint(
            "target_id", "test_run_id", name=op.f("uq_baseline_target_id_test_run_id")
        ),
    )
    op.create_index(
        "ix_baseline_target_compat",
        "baseline",
        ["target_id", "test_type", "target_concurrency"],
        unique=False,
    )
    op.create_index(op.f("ix_baseline_target_id"), "baseline", ["target_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_baseline_target_id"), table_name="baseline")
    op.drop_index("ix_baseline_target_compat", table_name="baseline")
    op.drop_table("baseline")
    # `test_type` is deliberately NOT dropped: test_plan still uses it. The
    # enum was created by the initial migration and is that migration's to
    # remove.
    # ### end Alembic commands ###
